### ISSUE TITLE
sanitize_test.go compile errors?

### ISSUE THREAD

**Issue by mr-ma** [shurcooL/github_flavored_markdown#7]
Maybe I'm doing sth wrong, but I'm not able to run sanitize tests...

go test src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go 
```\# command-line-arguments
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:51: undefined: renderer
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:89: undefined: Markdown
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:99: undefined: Markdown
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:107: undefined: Markdown
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:115: undefined: Markdown
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:123: undefined: Markdown
src/github.com/shurcooL/github_flavored_markdown/sanitize_test.go:132: undefined: Markdown
FAIL	command-line-arguments [build failed]```

Could this possibly be an issue?

**Comment by shurcooL** [comment]
The Travis build is [passing](https://travis-ci.org/shurcooL/github_flavored_markdown/builds/76805318), so that is an indicator that tests are passing.

It appears you're providing incorrect parameter to `go test`. It takes a Go package import path, not a filename path. Try this:

```
go test -v github.com/shurcooL/github_flavored_markdown
```

You can read more about the `go test` command at http://golang.org/cmd/go/#hdr-Test_packages.

**Comment by shurcooL** [comment]
@mr-ma, have you tried the above command? Did it work?

**Comment by mr-ma** [comment]
Yes, sorry man bad. newbie in go world ;)

**Comment by shurcooL** [comment]
No worries. :)
